# Generated by Django 4.2 on 2023-04-14 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Receita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=8)),
                ('data', models.DateField()),
                ('descricao', models.CharField(blank=True, max_length=200)),
                ('categoria', models.CharField(choices=[('INVESTIMENTO', 'Investimento'), ('PRESENT', 'Presente'), ('PREMIO', 'Prêmio'), ('SALARIO', 'Salário'), ('OUTROS', 'Outros')], max_length=20)),
                ('comprovante', models.FileField(upload_to='comprovantes/')),
            ],
        ),
    ]
