# Generated by Django 4.2 on 2023-04-14 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0002_despesa_alter_receita_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='receita',
            name='descricao',
            field=models.CharField(blank=True, max_length=200, verbose_name='Descrição:'),
        ),
    ]
